Dan.Common/Models/ProvideOwnTokenRequirement.cs, Dan.Core/FuncDirectHarvester.cs, Dan.Core/FuncEvidenceHarvester.cs, Dan.Core/Services/EvidenceHarvesterService.cs, Dan.Core/Services/Interfaces/IEvidenceHarvesterService.cs, Dan.Core/Services/Interfaces/IRequestContextService.cs, Dan.Core/Services/RequestContextService.cs, Dan.Core/Services/RequirementValidationService.cs
Created a new requirement in common.models. This requires the user to either provide a token in the header, mark their token as reusable, or set digdir as the provider.
Moved GetEvidenceHarvesterOptionsFromRequest from the EvidenceHarvesterService to RequestContextService.
Created validation of ProvideOwnTokenRequirement in the RequirementValidationService.
=> New authentication requirement - ProvideOwnTokenRequirement

Dan.Common/Services/EntityRegistryService.cs
Add whitelist for organization numbers that the heuristics fail to recognize as public sector. Case in point: https://data.brreg.no/enhetsregisteret/api/enheter/971032146
=> Add whitelist for organization numbers to IsPublicSector

Dan.Core/Middleware/DiagnosticsHeaderInjectionMiddleware.cs, Dan.Core/Middleware/FunctionContextAccessorMiddleware.cs, Dan.Core/Program.cs, Dan.Core/Services/AvailableEvidenceCodesService.cs, Dan.Core/Services/FunctionContextAccessor.cs, Dan.Core/Services/Interfaces/IFunctionContextAccessor.cs, Dan.Core/Services/Interfaces/IRequestContextService.cs, Dan.Core/Services/RequestContextService.cs
Adds a mechanism akin to HttpContextAccessor allowing access to scoped dependencies (usually the HTTP request) from singleton services, utilizing middleware as a workaround mechanism pending more official support in the worker-sdk. Also adds a cache diagnostics header being set first time GetAvailableEvidenceCodes is being called.
=> Add IFunctionContextAccessor + cache diagnostics headers

Dan.Common/Enums/ErrorCode.cs, Dan.Core/Dan.Core.csproj, Dan.Core/Exceptions/InvalidJmesPathExpressionException.cs, Dan.Core/Extensions/ExceptionExtensions.cs, Dan.Core/Extensions/HttpExtensions.cs, Dan.Core/FuncDirectHarvester.cs, Dan.Core/FuncEvidenceHarvester.cs, Dan.Core/FuncOpenData.cs, Dan.Core/Helpers/JmesPathTransfomer.cs
This adds support for [JMESPath](https://jmespath.org/) via https://github.com/jdevillard/JmesPath.Net . A URL parameter, `query`, is added for all harvest endpoints (ignored if using envelope) as well as metadata-endpoints.
=> Add support for JMESPath transformation

Dan.Common/Enums/EvidenceValueType.cs, Dan.Core.UnitTest/EvidenceHarvesterServiceTest.cs, Dan.Core/FuncDirectHarvester.cs, Dan.Core/FuncEvidenceHarvester.cs, Dan.Core/Services/EvidenceHarvesterService.cs, Dan.Core/Services/Interfaces/IEvidenceHarvesterService.cs
This adds support for harvesting non-encoded/enveloped binary evidence values from plugins, which performs better on larger non-structured files since we avoid a lot of JSON marshalling. This also implements streaming of said binaries, however the  out-of-process functions model does not yet support this, so the entire content needs to be buffered on each hop (plugin worker -> plugin host -> core worker -> core host -> client). This causes significant delay before the first byte is received at the client. This change, however, by avoiding Base64-encoding, mitigates this.
=> Add support for streaming non-encoded binaries from plugins

Dan.Common/Dan.Common.csproj, Dan.Common/Extensions/HostBuilderExtensions.cs, Dan.Core/Dan.Core.csproj, Dan.Core/FuncMetadataEvidence.cs, Dan.Core/Helpers/VersionHelper.cs, Dan.Core/Models/VersionInfo.cs, Dan.Core/Program.cs
Bumps preview versions of worker-based functions dependencies, and add code to handle Application Insights-logging
=> Attempt to fix logging in plugins via ConfigureDanPluginDefaults

Dan.Core/Program.cs
Log analytics show that skatt and tilda regularly hit 15-20 seconds cold start times, causing the evidence code refresh to treat it as timed out/dead. As a triaging measure pending optimized start up times in these plugins, we up the timeout value to 25 seconds.
=> Up timeout for plugins to respond to evidence code refresh

.gitignore, Dan.Core/Config/Settings.cs, Dan.Core/Middleware/AuthenticationMiddleware.cs, README.md
Remove MaskinportenAuxUrl and MaskinportenAuxWellknownUrl settings
https://github.com/data-altinn-no/core/issues/86
Updated README.md with correct local cosmosdb database name
=> feat: remove maskinportenaux settings #86

Dan.Common.UnitTest/Dan.Common.UnitTest.csproj, Dan.Common/Dan.Common.csproj, Dan.Core.UnitTest/Dan.Core.UnitTest.csproj, Dan.Core.UnitTest/Helpers/AssertHelper.cs, Dan.Core.UnitTest/Startup.cs, Dan.Core/Dan.Core.csproj
Simple upgrade to .NET 8, upgraded azure functions sdk package to support .NET 8 (why this was a minor version upgrade idk but functions do be functions)
Remove an unused code snippet that caused a warning, added a public keyword to class that was decorated with attribute that causes warning if not public
=> feat: upgrade project to .NET 8

Dan.Common/Dan.Common.csproj, Dan.Common/Extensions/EvidenceHarvesterRequestExtension.cs, Dan.Common/Extensions/HostBuilderExtensions.cs, Dan.Core/Dan.Core.csproj, Dan.Core/Program.cs
Ref https://github.com/data-altinn-no/core/pull/71
The non-preview version of implementing application insights has changed a bit, instead of configuring the worker builder, it is registered to the service container.
See MS docs, based it off that: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#application-insights
=> chore(deps): upgrade application insights packages out of preview version

Dan.Core/ServiceContextTexts/DanTestServiceContextTextTemplate.cs, Dan.Core/Services/ServiceContextService.cs
In order to test the consent flow of the DAN-test data sets, the service context need text templates.
=> feat: add service context text templates to dantest

.github/workflows/core-ci.yaml, .github/workflows/core-cicd.yaml
#130 
The deploy pipeline in the deploy-actions repo has a setting for running e2e tests which is really only used by core.
Copied that pipeline here, might consider moving the e2e pipelines too if it's only core that uses it.
Looked into having e2e tests run after staging is deployed without needing approval again for that, but looking at a response here: https://github.com/orgs/community/discussions/68403, I'm not sure how straight forward that is. Let's just start with getting the pipeline working as expected in core for now?
=> ci: move ci/cd pipeline to repo

Dan.Core/Extensions/HttpExtensions.cs
Sjøfart-plugin returns skipsregister historical data in json array format, not stringified json.
This adds support if an evidence value set to JsonSchema is returned as JArray or JObject it still works if envelope is set to false
=> feat: support jarray and jobject as jsonschema evidencevalue sources

Dan.Core/Extensions/HttpExtensions.cs, Dan.Core/Helpers/JsonConverters/KeyValueListAsObjectConverter.cs
Tilda has multiple evidence values with the same key (tilsynsrapporter). This caused issue with envelope=false, as that made use of a hash table to serialize the evidence values before applying jmespath expression.
Adding a custom converter that serializes a keyvaluepair list to the same result as a hashtable would. This means the json can have duplicate properties, which isn't malformed, but not exactly the best practice either, but it will behave as expected
https://github.com/data-altinn-no/core/issues/10
=> feat: allow duplicate evidence value keys

Dan.Core/Services/ServiceContextService.cs
Add new service context for altinn studio apps - all datasets will require client-provided authentication token to be used against the datasources
=> added altinn studio apps servicecontext

Dan.Common.UnitTest/Dan.Common.UnitTest.csproj, Dan.Common.UnitTest/Extensions/EvidenceHarvesterRequestExtensionTests.cs, Dan.Common/Extensions/EvidenceHarvesterRequestExtension.cs, Dan.Core.UnitTest/Dan.Core.UnitTest.csproj
TryGetParam fails to parse 1 as int, because it expected params to come in string format.
Now allows for most suitable number formats as well as string to be provided and we'll do best effort parsing
=> fix: ensure number and decimal does best effort parsing

Dan.Common/Models/EvidenceCode.cs, Dan.Common/Models/ServiceContext.cs
feat: add license property to evidencecode
Will be used to display license on docs
=> feat: add license property to evidencecode

Dan.Core/Config/Settings.cs, Dan.Core/Dan.Core.csproj, Dan.Core/FuncUsageStatistics.cs, Dan.Core/Models/MonthlyUsageStatistics.cs, Dan.Core/Models/YearlyUsageStatistics.cs, Dan.Core/Program.cs, Dan.Core/Services/UsageStatisticsService.cs, Dan.Core/local.settings.json.template
https://github.com/data-altinn-no/core/issues/149
Three endpoints, month, year, all. Month fetches usage last thirty days. Yearly and all groups statistics per month, goes back to january 1st of the previous year. All fetches.. well, all!
=> feat: add endpoints for getting servicecontext usage

Dan.Common/Constants.cs, Dan.Common/Enums/ErrorCode.cs, Dan.Common/Extensions/HostBuilderExtensions.cs, Dan.Common/Handlers/PluginAuthorizationMessageHandler.cs, Dan.Common/Services/DanPluginClientService.cs, Dan.Core/Program.cs, Dan.Core/Services/AvailableEvidenceCodesService.cs, Dan.Core/Services/EvidenceHarvesterService.cs, Dan.Core/Services/EvidenceStatusService.cs, Dan.PluginTest/Config/PluginConstants.cs, Dan.PluginTest/Config/Settings.cs, Dan.PluginTest/Metadata.cs, Dan.PluginTest/Plugin.cs
feat: add support for azure auth to plugins
A DelegatingHandler is added to http clients that go towards plugins, allowing us to set up app authentication in Azure. Appsetting `"PluginScopes"` must be added, and said scope must be configured in the plugin auth settings.
Also adding  DanPluginClientService which allows for plugin-to-plugin communication, using the same handler described above.
=> feat: add support for azure auth to plugins

Dan.Common/Config/PluginKeyVault.cs, Dan.Common/Dan.Common.csproj, Dan.PluginTest/Config/PluginConstants.cs, Dan.PluginTest/Config/Settings.cs, Dan.PluginTest/Metadata.cs, Dan.PluginTest/Plugin.cs, Dan.PluginTest/Program.cs
Add pluginkeyvault class to Dan.Common that can be used to get values from keyvault. Based on the Trad implementation
=> feat: add plugin keyvault class in common

Dan.Core.UnitTest/AvailableEvidenceCodesServiceTest.cs, Dan.Core/Services/AvailableEvidenceCodesService.cs
Increased the memory cache time for dancore to 10 minutes. Since it force refreshes every 5 minutes, this should be sufficient to avoid fall outs.
Also removed a part of the code that cached the evidencecodes in redis, but that was handled by polly via the policyregistry, making the code snippet unused and confusing
=> feat: increase caching time for ec

Dan.Common/Services/PluginCredentialService.cs
=> diag: add diag for token fetching
